### ISSUE TITLE
Implement OIDC state parameter

### ISSUE THREAD

**Issue by MartinFlores751** [irods/irods_client_http_api#121]
OAuth 2.0 has an optional 'state' variable that may be passed along in the Authorization code grant, which helps combat cross-site request forgery.

We should implement this.

Additionally, we may consider the OpenID Connect 'nonce' parameter.

**Comment by korydraughn** [comment]
Please close if completed.

**Comment by MartinFlores751** [comment]
Forgot the additional configuration documentation, reopening until done with that.
