### ISSUE TITLE
Use the same property name to reference GenQuery search results

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#132]
GenQuery1 returns a JSON structure where the rows are mapped to a key called `rows`.

GenQuery2 returns a JSON structure where the key is called `results`.

`results` makes more sense give GenQuery2 can return the generated SQL instead of database rows.

This also applies to the specific query JSON output structure.

Alternatively, the HTTP API could use a different property for SQL output.

**Comment by trel** [comment]
Let’s survey some other tools…

Either choice is good enough so far…
