### ISSUE TITLE
Server segfaults on `parse_url`

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#139]
## Bug Report
I attempted to reach the /authenticate endpoint by typing the URL in Google Chrome and before I got the prompt, the server crashed with the following.
```
[2023-11-04 08:12:16.669] [P:2566900] [error] [T:2566985] parse_url: curl_url_get(CURLUPART_QUERY) error: 16
Segmentation fault (core dumped)
```

Below is what I typed in the browser.
```
http://localhost:9000/irods-http-api/0.1.0/authenticate
```

**Comment by korydraughn** [comment]
This was caused by my config not having appropriate OIDC settings defined. The implementation currently replies on a GET request as part of the OIDC flow.

If we want to allow users to authenticate using Basic auth in a browser, we'll need to adjust how the HTTP API handles OIDC. Perhaps an op param can be introduced or a separate endpoint.

**Comment by trel** [comment]
So we definitely need to put bumpers on that use case (missing config items).

A separate endpoint might be easier / separate the concerns.

**Comment by korydraughn** [comment]
Supporting authentication using the following syntax is not a requirement of the HTTP API.
```
http://<username>:<password>@localhost:9000/irods-http-api/0.1.0/authenticate
```

For that reason, this issue has been resolved since attempting to do what's described in this issue no longer results in the server crashing.

**Comment by korydraughn** [comment]
Need to add tests for this.
