### ISSUE TITLE
Consider having the HTTP API be an OAuth resource server instead of a OAuth client

### ISSUE THREAD

**Issue by MartinFlores751** [irods/irods_client_http_api#155]
Use [OAuth's RFC Figure 1](https://datatracker.ietf.org/doc/html/rfc6749#section-1.2) for a simple visual reference.

Currently, the HTTP API is treated as on OAuth client. This requires the HTTP API to handle multiple OAuth flows, token refresh, and additional complexities in handling various OAuth/OIDC items. (This isn't to say every feature is currently handled, rather, if we continue on, we would likely need to support these additional features.)

By treating the HTTP API as a resource server, the HTTP API may no longer need to handle all of these cases.
It simply accepts OAuth access tokens, verifies them, and verifies there is a mapping between the OAuth user and an iRODS user.
Additionally, grants such as the authorization code grant could be implemented in a much more user-friendly way, compared to how they are currently implemented.
This may also allow the HTTP API to use the OAuth access tokens directly instead of converting it into an alternative 'internal HTTP API token', leaning more on the OAuth server to determine when the token expires.

However, this would mean clients using the HTTP API wishing to support OAuth would need to handle all the desired grants themselves.
Additionally, by no longer being a client, there may be some complications in the mapping of users. Some work needs to be done to verify whether this is true, however, given the current usage of OAuth/OIDC in the HTTP API, it is unlikely to cause issues.

**Comment by MartinFlores751** [comment]
Glad to see you're interested.

>  I am just wondering whether your proposal is being considered for the future or there are no concrete plans at the moment.

I am currently working on implementing this feature. When it is released, you should be able to choose between running the HTTP API in 'OAuth client' mode, or 'OAuth protected resource server' mode.

>  I am thinking of, for instance, an iRODS web app which could retrieve directly an access token from an oidc provider and use that in the backend for future API calls. Single sign-on would also work.

When it releases, you should be able to do this. The sign-in experience should be better, too.

**Comment by MartinFlores751** [comment]
Some notes on possible limitations/issues:

There may be some issues getting this to work with Google's OpenID Provider.

``` mermaid
  sequenceDiagram
      autonumber

      actor HTTP API Consumer
      participant OpenID Provider
      participant iRODS HTTP API

      %% User Authentication
      HTTP API Consumer ->> OpenID Provider: POST /<OpenID Authentication>
      OpenID Provider -->> HTTP API Consumer: 302 FOUND /authenticate (payload)

      %% Exchange temp token for OIDC token
      HTTP API Consumer ->> OpenID Provider: POST /token (payload)
      OpenID Provider -->> HTTP API Consumer: 200 OK (OpenID Token)

      %% Use the API
      HTTP API Consumer ->> iRODS HTTP API: GET /collections (Access Token)
      iRODS HTTP API ->> OpenID Provider: POST /introspection (Access Token)
      OpenID Provider -->> iRODS HTTP API: 200 OK (JSON)
```

The issue is that Google doesn't seem to provide (6), an introspection endpoint, to the best of my knowledge.
The one that they do provide seems to be for debugging only.

Additionally, another method I'm aware of for verifying the access token, is not supported since the access token is not a JWT.
More information on this method can be found here: https://datatracker.ietf.org/doc/rfc9068/

**Comment by korydraughn** [comment]
Do you have a link to the Google documentation which talks about the introspection endpoint being for debugging purposes only?

**Comment by MartinFlores751** [comment]
> Do you have a link to the Google documentation which talks about the introspection endpoint being for debugging purposes only?

I believe it should be this: https://developers.google.com/identity/sign-in/android/backend-auth#calling-the-tokeninfo-endpoint

**Comment by MartinFlores751** [comment]
Thank you for the documentation.
It looks like the `access_token` query is what is needed for it to work.

I'll test it in a moment just to be sure it works.
