### ISSUE TITLE
Server version info contains sha that makes confusing version in url of api

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#160]
### What did you try to do?
I tried to use the version of api in the url. 

### Expected behavior
An explicit documentation somewhere about what to use in url. Or expected to see only the version number in the result of `irods_http_api --version`.
### Observed behavior (including steps to reproduce, if applicable)

```
[irods@dev-u0137480 irods]$ irods_http_api --version
irods_http_api v0.1.0-38d67aa
[irods@dev-u0137480 irods]$ curl -X POST -u rods:rods http://127.0.0.1:9000/irods-http-api/v0.1.0-38d67aa/authenticate -v

...
< HTTP/1.1 404 Not Found
< Server: irods_http_api/0.1.0 [38d67aa5ab798952450dc4429c20d82586a375e8]
< Content-Type: application/json
< Content-Length: 0
...
```

**Comment by korydraughn** [comment]
Very interesting. It never occurred to me the info from `--version` would be used.

That value is just giving you version information about the binary.

We'll add a few words to the API documentation to clear up the confusion.

**Comment by korydraughn** [comment]
Use the following instead.
```
http://127.0.0.1:9000/irods-http-api/0.1.0/authenticate
```
