### ISSUE TITLE
Removing OIDC section results in parse error

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#161]
### What did you try to do?
I wanted to use the basic schema for now to be authenticated. For this, I removed OIDC section from config.json as stated in the readme.

### Expected behavior
Expected to see the server initializing without an error.

### Observed behavior (including steps to reproduce, if applicable)
```
[irods@dev-u0137480 irods]$ irods_http_api config.json
Error: [json.exception.parse_error.101] parse error at line 15, column 9: syntax error while parsing object key - unexpected '}'; expected string literal
```

However if I keep the following string (an empty oidc key), it starts up.
 ```
"oidc": {
           }

```

**Comment by korydraughn** [comment]
Please post the config _(with sensitive info removed)_ which caused the error.

**Comment by mstfdkmn** [comment]
Sorry! Looks like I forgot to delete "," just after the `basic` section. We can close this. Thanks.
