### ISSUE TITLE
Can `irods_username` field in custom claim be configured?

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#163]
## Feature/Question

Regarding with "Currently, the server looks for the custom claim `irods_username` in the ID Token.", we would like to be able to set "preferred_username" instead of "irods_username". Is this possible?

**Comment by korydraughn** [comment]
@MartinFlores751 Please close if completed.

**Comment by korydraughn** [comment]
Consider adding a note to the README about this enhancement.

**Comment by trel** [comment]
need a note in the `irods_username` section that points out this configuration option.
