### ISSUE TITLE
authenticate endpoint doesnt handle wrong request method (GET)

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#165]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
Accidentally I called `GET` against the `/authenticate` endpoint.

### Expected behavior
Nothing. Expected the server is running normal and the client should encounter nothing.

### Observed behavior (including steps to reproduce, if applicable)

When the client called this,
```
[irods@dev-u0137480 go-http-client]$ curl -X GET -u rods:rods http://localhost:9000/irods-http-api/0.1.0/authenticate
curl: (52) Empty reply from server
```

The server crashed with:
```
[2023-12-15 13:50:58.641] [P:2326977] [error] [T:2327026] parse_url: curl_url_get(CURLUPART_QUERY) error: 16
Segmentation fault (core dumped)
```
The server is configured with the basic authentication schema. Might be related to #139?

**Comment by trel** [comment]
Yuck.   We'll definitely shore that up.   Thanks.

**Comment by trel** [comment]
Yes, looks extremely related to #139.   Need more bumpers.
