### ISSUE TITLE
authenticate endpoint doesn't response error (401) to invalid credentials provided

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#167]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
For the server running with the basic authentication scheme configured, posted wrong credentials to the authenticate endpoint to get the token.
```
[irods@dev-u0137480 go-http-client]$ curl -X POST -u rods:wrong-pass http://localhost:9000/irods-http-api/0.1.0/authenticate
[irods@dev-u0137480 go-http-client]$
```

### Expected behavior
An error code in the client side and some also some logging in server.

### Observed behavior (including steps to reproduce, if applicable)
Nothing observed. Should the authenticate endpoint response with error (401) to invalid credentials provided?

**Comment by mstfdkmn** [comment]
I couldn't reproduce this with other languages. Probably I am not using curl correctly. Therefore closing this.

**Comment by trel** [comment]
Please share what you see with the `-v` verbose option.

**Comment by mstfdkmn** [comment]
I am getting what I should :)

```
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 9000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
* Server auth using Basic with user 'rods'
> POST /irods-http-api/0.1.0/authenticate HTTP/1.1
> Host: localhost:9000
> Authorization: Basic cm9kczpodW50ZXI=
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Server: irods_http_api/0.1.0 [38d67aa5ab798952450dc4429c20d82586a375e8]
< Content-Type: application/json
< Content-Length: 0
<
* Connection #0 to host localhost left intact

```
