### ISSUE TITLE
Most operations in collection endpoint not obeying irods permissions

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#168]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
I tried to list a collection that I don't have any permission.

### Expected behavior
I expected to see an error like "...does not exist or user lacks access permission or CAT_NO_ACCESS_PERMISSION".

### Observed behavior (including steps to reproduce, if applicable)
I can list and see the status of any collection as a regular irods user.

checking acl of a target collection:
```
[irods@dev-u0137480 go-http-client]$ ils -A /u0137480/home/bob
/u0137480/home/bob:
        ACL - bob#u0137480:own
        Inheritance - Disabled
```

a user through the http-api can list that collection:
```
[mustafa@dev-u0137480 ~]$ curl http://dev-u0137480.irods.t.icts.kuleuven.be:9000/irods-http-api/0.1.0/collections -H 'Authorization: Bearer a48e0b4a-abe3-4763-bc95-9cece1da1694' --data-urlencode 'op=list' --data-urlencode 'lpath=/u0137480/home/bob' --data-urlencode 'recurse=0' -G
{"entries":["/u0137480/home/bob/go.sum"],"irods_response":{"status_code":0}}
```

but the same user cannot list via other clients like iCommands:
```
[mustafa@dev-u0137480 ~]$ ils -A /u0137480/home/bob
remote addresses: 10.0.2.100 ERROR: lsUtil: srcPath /u0137480/home/bob does not exist or user lacks access permission
```

**Comment by mstfdkmn** [comment]
I think other operations like `remove`, `create` dont pay attention to the irods permissions either. 

```
[mustafa@dev-u0137480 ~]$ curl http://localhost:9000/irods-http-api/0.1.0/collections -H 'Authorization: Bearer a48e0b4a-abe3-4763-bc95-9cece1da1694' --data-urlencode 'op=create' --data-urlencode 'lpath=/u0137480/home/rods/test1' --data-urlencode 'create-intermediates=0'
{"irods_response":{"status_code":0}}
```

**Comment by korydraughn** [comment]
Which user does that bearer token identify?

A quick test indicates the permissions are being honored as expected.

Keep in mind, the bearer token represents a single authenticated user. As long as the token hasn't expired, it will always resolve to the authenticated user (i.e. the username/password passed to /authenticate).
```bash
# Authenticate as alice, a rodsuser.
$ token=$(curl -X POST -su alice:apass 'http://localhost:9000/irods-http-api/0.1.0/authenticate')
# The UUID stored in "token" will always represent alice until it expires.
$ echo $token
bd142c0c-c831-4ca3-a5ca-7e2e8dea03c4
# Attempt to list the contents of the rods user's home collection.
# This fails because alice does not have permission to read the rods user's home collection.
$ curl -G -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/collections' \
    --data-urlencode 'op=list' \
    --data-urlencode 'lpath=/tempZone/home/rods' | jq
{
  "irods_response": {
    "status_code": -170000
  }
}
```

**Comment by mstfdkmn** [comment]
My bad! Sorry, looks like I used the token of rodsadmin as a regular user. :(

**Comment by korydraughn** [comment]
rodsadmin don't need permission to list collections. They are allowed to look around freely. They just can't read/write data that doesn't belong to them.

**Comment by korydraughn** [comment]
That curl call needs to use the HTTP POST method. You passed `-G`. If you remove the `-G`, what happens?

Regardless, the HTTP API should return an HTTP error when the `op` and HTTP method are incompatible. I'll open an issue for that.

**Comment by korydraughn** [comment]
Created #171 to address incompatible HTTP methods and `op` params.

I imagine if `-G` is removed, the call will make it to the iRODS server and cause an error to be logged. Please give that a try and let us know what happens.

**Comment by mstfdkmn** [comment]
It is exactly like how you expected. On the client side no error but similar errors of other clients in irods log.

```
[irods@dev-u0137480 irods]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/collections' --data-urlencode 'op=create' --data-urlencode 'lpath=/u0137480/home/rods/test2' --data-urlencode 'create-intermediates=0'
{"irods_response":{"status_code":0}}
```
```
http-api stdout | [2023-12-18 17:12:57.002] [P:450] [info] [T:503] op_create: client_info.username = [mustafa]
irods stdout | {"log_category":"database","log_level":"info","log_message":"chlRegColl cmlExecuteNoAnswerSql(rollback) succeeded","request_api_name":"COLL_CREATE_AN","request_api_number":681,"request_api_version":"d","request_client_user":"mustafa","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.1","server_host":"dev-u0137480.irods.t.icts.kuleuven.be","server_pid":33378,"server_timestamp":"2023-12-18T16:12:57.014Z","server_type":"agent","server_zone":"u0137480"}
irods stdout | {"log_category":"legacy","log_level":"error","log_message":"rsMkCollR: rsCollCreate failed for /u0137480/home/rods, status =-818000","request_api_name":"COLL_CREATE_AN","request_api_number":681,"request_api_version":"d","request_client_user":"mustafa","request_host":"10.0.2.100","request_proxy_user":"rods","request_release_version":"rods4.3.1","server_host":"dev-u0137480.irods.t.icts.kuleuven.be","server_pid":33378,"server_timestamp":"2023-12-18T16:12:57.014Z","server_type":"agent","server_zone":"u0137480"}
```

**Comment by korydraughn** [comment]
So the iRODS server logged an error, good. But did the HTTP API actually return a status_code of 0? I'd expect the iRODS error to be captured in the JSON response.

**Comment by korydraughn** [comment]
Turns out the HTTP API doesn't report an error when there is a permission error.

I know why. We'll get a fix in for that too.

**Comment by korydraughn** [comment]
Created #172 and #173.

**Comment by korydraughn** [comment]
#172 and #173 have been resolved.

Closing.
