### ISSUE TITLE
`no-trash` and `unregister` params are optional for remove operation in /data-objects endpoint

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#175]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
I tried to remove a data object without specifying `no-trash` and `unregister`.

### Expected behavior
I expected to see wrong input error and so that no removal of the data object.

### Observed behavior (including steps to reproduce, if applicable)
The data object in question has been removed - actually moved to the trash. If this is a normal behavior, it would be nice to see "optional" labels in the API documentation.

```
[irods@dev-u0137480 go-http-client]$ ils myfile.txt
  /u0137480/home/rods/myfile.txt
[irods@dev-u0137480 go-http-client]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=remove' --data-urlencode 'lpath=/u0137480/home/rods/myfile.txt'
{"irods_response":{"status_code":0}}
[irods@dev-u0137480 go-http-client]$ ils /u0137480/trash/home/rods
/u0137480/trash/home/rods:
  myfile.txt
```

**Comment by mstfdkmn** [comment]
Actually seeing "unregister" as an option in `op=remove` looks a bit confusing. Because, unregister is normally another operation and using it here with "no-trash" (its default is 0) is a ?

**Comment by trel** [comment]
A default iRODS server's policy uses the trash - so a 'remove' operation will honor that setting and put the data object in the trash.

Unregister should probably be a separate operation - I think I agree.   We came to the same conclusion when splitting 'iunreg' from 'irm' a few years ago.

**Comment by alanking** [comment]
Linking issue here so the reasoning/discussion is handy: https://github.com/irods/irods/issues/4506

**Comment by korydraughn** [comment]
The documentation doesn't use the word, optional, because defaults are included.

Given there is a `register` operation, it makes sense to provide an `unregister` operation too.

Will get that implemented.
