### ISSUE TITLE
How to verify checksum?

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#179]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
Tried to verify checksum as advertised in its API.md document.

### Expected behavior
Expected to see response with 200.

### Observed behavior (including steps to reproduce, if applicable)
HTTP Error: 400 Bad Request

`[irods@dev-u0137480 go-http-client]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=verify_checksum' --data-urlencode 'lpath=/u0137480/home/rods/myfile.txt' -v`

Could you point me what wrong is? Or can you share a an example running on your end? Btw, I could not see any test for checksum operations.

**Comment by alanking** [comment]
What you did looks correct to me, so I think we will need more information (though I'm certainly not an HTTP API expert). Do you have the whole response from the HTTP API? Was there a "status_message" or any "r_error_info"? Does the data object at `lpath` have a checksum already?

For reference, here's the API documentation: https://github.com/irods/irods_client_http_api/blob/main/API.md#verify_checksum That's mostly for easy access in the future - I know you've probably seen that. :)

Definitely need to at least add a test for `verify_checksum`, agreed. It seems that there used to be a basic test but it got lost in translation to python tests...
https://github.com/irods/irods_client_http_api/blob/5b7943f89bf0021693c0ae8ad1596be1d819410d/test.sh#L386-L391

**Comment by mstfdkmn** [comment]
Thanks Alan. There are two things:
- According to the test script you referred the `verify_checksum` operation should work with "GET" which is not mentioned in the API.md document and is what I tried too.
- But I am only getting/seeing the status code in response, nothing else.

```
[irods@dev-u0137480 go-http-client]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=calculate_checksum' --data-urlencode 'lpath=/u0137480/home/rods/myfile.txt'
{"checksum":"sha2:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=","irods_response":{"status_code":0}}[irods@dev-u0137480 go-http-client]$
[irods@dev-u0137480 go-http-client]$
[irods@dev-u0137480 go-http-client]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=verify_checksum' --data-urlencode 'lpath=/u0137480/home/rods/myfile.txt'
[irods@dev-u0137480 go-http-client]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=verify_checksum' --data-urlencode 'lpath=/u0137480/home/rods/myfile.txt' -G
{"irods_response":{"status_code":0}}
```

So, I think there are two issues in #179:
- The API.md should state that this is a query (add -G in curl)
- And should have tests.

Also, the third point might be that the result object can return the checksum sha2 even if the operation doesn't find inconsistencies in order to show clients explicitly that the data integrity is intact.

```
"results": {
        // Verification results. This object only exists if the operation found inconsistencies
        // between what's in storage and what's in the catalog.
    },
```

**Comment by korydraughn** [comment]
We'll make sure to add tests.
