### ISSUE TITLE
How do you get "registered": false in the response of op=stat operation on data-objects endpoint?

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#180]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
I tried to see "registered": false in the response of the `stat` operation. For this I tried to unregister. 

### Expected behavior
Always expected to see <"registered": true> because the operation runs for an logical path.

### Observed behavior (including steps to reproduce, if applicable)

```
[irods@dev-u0137480 go-http-client]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=stat' --data-urlencode 'lpath=/u0137480/home/rods/myfile.txt' -G
{"checksum":"sha2:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=","irods_response":{"status_code":0},"modified_at":1703013347,"permissions":[{"name":"rods","perm":"own","type":"rodsadmin","zone":"u0137480"}],"registered":true,"size":0,"type":"data_object"}
```

```
[irods@dev-u0137480 go-http-client]$ iunreg myfile.txt
[irods@dev-u0137480 go-http-client]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=stat' --data-urlencode 'lpath=/u0137480/home/rods/myfile.txt' -G
{"irods_response":{"status_code":-171000}}
[irods@dev-u0137480 go-http-client]$ ierror -171000
irods error: -171000 NOT_A_DATA_OBJECT
```

A bit confused with what exists [here](https://github.com/irods/irods_client_http_api/blob/main/API.md#response-16).

**Comment by alanking** [comment]
A data object must be registered in order to exist by definition, so... not sure what the field means in this case. It may exist for some other reason that I'm not aware of. @korydraughn will definitely know more.

**Comment by korydraughn** [comment]
The reason `registered` exists is due to special collections.

See https://github.com/irods/irods/issues/5133.

If you're not working with archive files, then you may be able to ignore that property. Its value depends on whether GenQuery finds a row for the path in the catalog.

**Comment by mstfdkmn** [comment]
Expected to see "Registered":true for all data objects uploaded (registered in catalogue) or only registered. The question was for in which circumstances should we expect to see false. If it is false, I think this means that the object is not known by irods, so the api cannot return anything in that case. a bit confused with seeing registered:false in docs.

**Comment by korydraughn** [comment]
Perhaps that property doesn't serve a good purpose for data objects. Renaming or removing it is certainly a possibility.

We'll investigate.

**Comment by korydraughn** [comment]
Circling back to this, `"registered"` **would** be false for situations involving `imcoll` (i.e. special collections). The reason being that the objects handled through `imcoll` will not have rows in the catalog. See the example below:
```
$ imkdir test.tar.imcoll
$ imcoll -m tar /tempZone/home/kory/test.tar /tempZone/home/kory/test.tar.imcoll
$ ils test.tar.imcoll
/tempZone/home/kory/test.tar.imcoll:
  C- /tempZone/home/kory/test.tar.imcoll/test
$ ils test.tar.imcoll/test
/tempZone/home/kory/test.tar.imcoll/test:
  185kb.bin
  101kb.bin
  f1
  f3
  109kb.bin
  f2
  1074kb.bin
  C- /tempZone/home/kory/test.tar.imcoll/test/asdfasdfasdf
  C- /tempZone/home/kory/test.tar.imcoll/test/y
  C- /tempZone/home/kory/test.tar.imcoll/test/b
  C- /tempZone/home/kory/test.tar.imcoll/test/dx
$ ils test.tar.imcoll/test -l
/tempZone/home/kory/test.tar.imcoll/test:
  kory         tarStr demoResc       189440 2024-04-23.16:55 & 185kb.bin
  kory         tarStr demoResc       103424 2024-04-23.16:55 & 101kb.bin
  kory         tarStr demoResc            0 2023-10-31.09:58 & f1
  kory         tarStr demoResc            0 2023-10-31.09:58 & f3
  kory         tarStr demoResc       111616 2024-04-23.16:55 & 109kb.bin
  kory         tarStr demoResc            0 2023-10-31.09:58 & f2
  kory         tarStr demoResc      1099776 2024-04-23.16:55 & 1074kb.bin
  C- /tempZone/home/kory/test.tar.imcoll/test/asdfasdfasdf  tarStructFile
  C- /tempZone/home/kory/test.tar.imcoll/test/y  tarStructFile
  C- /tempZone/home/kory/test.tar.imcoll/test/b  tarStructFile
  C- /tempZone/home/kory/test.tar.imcoll/test/dx  tarStructFile
$ iquest "select COLL_NAME, DATA_NAME where COLL_NAME = '/tempZone/home/kory/test.tar.imcoll/test'"
CAT_NO_ROWS_FOUND: Nothing was found matching your query
```

With that said, users will never see a value of false when using `stat` because the HTTP API will always execute the following code block.
https://github.com/irods/irods_client_http_api/blob/f524cec80187a003bf2956d7890b26b68b1d86c8/endpoints/data_objects/src/main.cpp#L1384-L1388

This means we can safely remove the `registered` property from the JSON response.
