### ISSUE TITLE
Rename source to same destination doesn't return any error

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#181]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
For both the collections and data-objects endpoints I tried to rename a source to the same destination.

### Expected behavior
I didn't expect to see response 200 and irods status code 0. I did expect to see `-339000` for data objects and `-837000` for collections. These are what iCommands returns.

### Observed behavior (including steps to reproduce, if applicable)

```
[irods@dev-u0137480 go-http-client]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=rename' --data-urlencode 'old-lpath=/u0137480/home/rods/myfile1.txt' --data-urlencode 'new-lpath=/u0137480/home/rods/myfile1.txt'
{"irods_response":{"status_code":0}}
```

**Comment by trel** [comment]
Also, we may not be able to change the way iCommands behave since they have been deployed for nearly 20 years in some cases.

**Comment by korydraughn** [comment]
@mstfdkmn Does that answer your question? Do you feel the behavior should be changed?

**Comment by mstfdkmn** [comment]
Yes it answers my question. For my curiosity, I will tomorrow try to see how the PRC handle this. 

No, I guess for us it may stay as it is unless we have serious reason.

**Comment by korydraughn** [comment]
Okay. Please leave an update here after you investigate the PRC.

**Comment by mstfdkmn** [comment]
As expected, the PRC returns errors while moving (renaming) an object to same location.
For us as said above the current behavior doesn't hurt anything now. However developers may want to catch this error in some situation to implement different logic, I guess.

```
>>> with iRODSSession(irods_env_file=env_file) as session:
...     pass
...
>>> session.data_objects.move("/u0137480/home/rods/myfile.txt", "/u0137480/home/rods/myfile.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/irods/manager/data_object_manager.py", line 551, in move
    response = conn.recv()
  File "/usr/local/lib/python3.6/site-packages/irods/connection.py", line 132, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.SAME_SRC_DEST_PATHS_ERR: None
>>> session.collections.move("/u0137480/home/rods/text", "/u0137480/home/rods/text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/irods/manager/collection_manager.py", line 130, in move
    response = conn.recv()
  File "/usr/local/lib/python3.6/site-packages/irods/connection.py", line 132, in recv
    raise get_exception_by_code(msg.int_info, err_msg)
irods.exception.SAME_SRC_DEST_PATHS_ERR: None

```
