### ISSUE TITLE
Copy an object to destination collection requires object name specified 

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#182]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
I wanted to copy a data object to a destination collection with its original name (without specifying any object name in the destination path).

### Expected behavior
Expected to see the data object is copied.

### Observed behavior (including steps to reproduce, if applicable)
The data object has not been copied with `INVALID_OBJECT_TYPE` error.

```
[irods@dev-u0137480 go-http-client]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=copy' --data-urlencode 'src-lpath=/u0137480/home/rods/myfile1.txt' --data-urlencode 'dst-lpath=/u0137480/home/rods/test'
{"irods_response":{"status_code":-171000,"status_message":"path does not point to a data object: INVALID_OBJECT_TYPE"}}
```

logs:
`http-api stdout | [2023-12-20 13:14:54.068] [P:284737] [error] [T:284785] op_copy: path does not point to a data object: INVALID_OBJECT_TYPE`

**Comment by trel** [comment]
I think this is behaving as expected.   We are not necessarily interested in reproducing the semantics of a shell (where the behavior is dependent on the target type).

Of course, this is all new, and we can have our minds changed :)

**Comment by mstfdkmn** [comment]
Would like to add something else. Not only iCommands but also the PRC does what proposed here. These are mature and mostly used clients (at least on our end). I tried to look at from the consistency point of view.

```
>>> with iRODSSession(irods_env_file=env_file) as session:
...      session.data_objects.copy("/u0137480/home/rods/myfile1.txt", "/u0137480/home/rods/test")
```

**Comment by trel** [comment]
This is a fair point.   Thanks.

**Comment by korydraughn** [comment]
What is being asked for can be achieved with the current implementation. It just requires the client to implement that functionality.

By forcing the user to be explicit, we make it more difficult for errors to be introduced.

**Comment by korydraughn** [comment]
One thing I need to investigate is how the /collections endpoint relates to this.

**Comment by korydraughn** [comment]
The functionality highlighted in this issue is a feature of the clients, not the iRODS API.

This is out of scope for the project. Closing.
