### ISSUE TITLE
Consider adding upload and download operations on /data-objects endpoint

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#184]
- [x] read
- write (see #208)
---
## Feature / Question

There are `read` and `write` operations but there is no get/download and put/upload functionality for a data object. Did you decide that get and put are tasks of developers who will use the api? Or this was in you todo? Just wanted to highlight this fact.

**Comment by trel** [comment]
indeed - same request as @olegkap

**Comment by korydraughn** [comment]
This is partially about where the HTTP API should sit in the stack.

If the HTTP API sits behind a server, then `read`/`write` become easy to manage. If a browser is talking directly to the HTTP API, then things become slightly more difficult because the web page / javascript has to handle it.

We're planning on relaxing the requirements so that `read` and `write` are easier to use from javascript.

**Comment by mstfdkmn** [comment]
One input for our possible usage context: in the first place we are thinking to use http-api as service for [rirods](https://github.com/irods/irods_client_library_rirods), so read and write look part of that client's development process. But in the far future we are thinking to expose the api for parties interested in developing their local portal projects.

**Comment by korydraughn** [comment]
Excellent. We're certainly interested in making things better. Keep the feedback coming.

The next release will have improved support for reading and hopefully writing.

**Comment by korydraughn** [comment]
The read operation has been simplified. It now supports streaming like the C++ REST API.

We'll leave this open until we reach a decision about the write operation.

**Comment by trel** [comment]
if `write` takes more time to work out, we can create a new issue so we can close this one for 0.2.0.

**Comment by korydraughn** [comment]
Handling `write` is definitely going to take some time.

Will open a new issue for that.

**Comment by korydraughn** [comment]
Created #208.

Will adjust this issue and close.
