### ISSUE TITLE
Trying to read non existent object doesn't return an error

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#185]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
Tried to read non-existing object. Tried to read an object that the user doesn't have access.

### Expected behavior
Expected to see `-358000` or `-818000` in irods response.

### Observed behavior (including steps to reproduce, if applicable)

```
[mustafa@dev-u0137480 ~]$ curl -H "Authorization: Bearer $token" 'http://localhost:9000/irods-http-api/0.1.0/data-objects' --data-urlencode 'op=read' --data-urlencode 'lpath=/u0137480/home/mustafa/myfile1.txt' --data-urlencode 'count=6' -G
[mustafa@dev-u0137480 ~]$

```

**Comment by trel** [comment]
What does this show with `-v`?    a 404?

**Comment by korydraughn** [comment]
The HTTP API uses dstream to read/write data objects. The dstream library does not expose iRODS error codes. It only allows you to check the state of the stream object (i.e. good, bad, fail, etc). This matches the behavior of `std::fstream` which is provided by the C++ standard.

So, we can't give the exact reason for why the read failed (yet).

Our only options are ...
- Use the C API directly
- Return a different HTTP status code
- Make dstream capture error codes in iRODS 4.3.2

**Comment by korydraughn** [comment]
With #184, we made the read operation simpler. That change also resolved this issue (a little).

Notice the HTTP status code returned in the example.
```
$ curl 'http://localhost:9000/irods-http-api/0.1.0/data-objects' \
   -H "Authorization: Bearer $token" \
  --data-urlencode 'op=read' \
  --data-urlencode 'lpath=/tempZone/home/rods/doesnotexist' -Gv                                                                                                                                                                      

*   Trying 127.0.0.1:9000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /irods-http-api/0.1.0/data-objects?op=read&lpath=%2FtempZone%2Fhome%2Frods%2Fdoesnotexist HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization: Bearer ce843927-acba-47ca-a81e-9276ddc4710a
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Server: irods_http_api/0.1.0 (c93ed1e317a473db6c8771a730837457c7856d31)
< Content-Type: application/json
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

Because reading a data object is handled via a GET request, we can't return a JSON response. We must rely on the HTTP status codes.

The question now is should we return a 4XX status code rather than 500?

I'm leaning towards a 4XX status code.

Thoughts?

**Comment by trel** [comment]
500 is internal error.  That would be inappropriate here.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes:
- 4xx client error – the request contains bad syntax or cannot be fulfilled
- 5xx server error – the server failed to fulfil an apparently valid request

I think for this we're looking at a basic 404.

**Comment by korydraughn** [comment]
404 sounds reasonable.

I think there are a few places in the read operation where we need to pick a more appropriate status code.

Will investigate.
