### ISSUE TITLE
Bearer token lifetime

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#187]
## Bug Report / Question

I have a basic authentication scheme configured. Although I am sure the server did not restarted and only one user was authenticated, time to time (I was not able to figure out pattern or time) I came across with a need to be reauthenticated.

I didn't understand anything about this in repo. When does the token fetched expires? During writing as chunk by chunk, is there a possibility to see it  as expired? I mean for each talk to server should the user get reauthenticated?

Logs:

`http-api stdout | [2023-12-22 16:31:28.022] [P:681203] [error] [T:681203] resolve_client_identity: Could not find bearer token matching [41eba753-1c80-4a18-a6f6-247bd4ee58cb].`

**Comment by korydraughn** [comment]
A few things ...
- The lifetime of a token is never extended
- The lifetime of a token obtained via Basic auth is defined by the config option at  `/http_server/authentication/basic/timeout_in_seconds`
    - The OIDC configuration also contains an option for this _(this may change in the future)_
- The HTTP API will return a **401 Unauthorized** if the bearer token cannot be resolved
    - Checking for that HTTP status code is the key to detecting when the client needs to be reauthenticated

We'll expand the API documentation to include words about this.

**Comment by mstfdkmn** [comment]
> The lifetime of a token obtained via Basic auth is defined by the config option at /http_server/authentication/basic/timeout_in_seconds

Ahh okay thanks. I will test this.
