### ISSUE TITLE
Define common JSON response structure

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#19]
## Ideas

The structures listed are in no particular order of preference.

### Structure 1
```json
{
  "irods_error_code": 0,
  "irods_message": "message"
}
```

### Structure 2
```json
{
  "irods_return_code": 0,
  "irods_message": "message"
}
```

### Structure 3
```json
{
  "irods_code": 0,
  "irods_message": "message"
}
```

### Structure 4
```json
{
  "irods_response": {
    "error_code": 0,
    "message": "message"
  }
}
```

### Structure 5
```json
{
  "irods_response": {
    "return_code": 0,
    "message": "message"
  }
}
```

### Structure 6
```json
{
  "irods_response": {
    "code": 0,
    "message": "message"
  }
}
```

**Comment by korydraughn** [comment]
We agree that structures 4, 5, and 6 are the best options.

Consider the following alternatives for `error_code`, `return_code`, and `code`:
- `status_code`
- `result_code`

**Comment by korydraughn** [comment]
Does anyone have any strong opinions on this?

If what's provided by the API today isn't sufficient, perhaps the following is better.
```json
{
  "irods_response": {
    "status_code": 0,
    "status_message": "string"
  }
}
```

I'd like to nail this down for 0.1.0 so no one has to change things in the future.

**Comment by trel** [comment]
I like your structure 7.   Let's do it.
