### ISSUE TITLE
write op of /data-objects opens and writes

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_http_api#191]
### iRODS Version, OS and Version
4.3.1, almalinux8

### What did you try to do?
I tried to write chunk by chunk.

### Expected behavior
I was expecting to find a way to create (open) an object first and write chunk by chunk and lastly auto close with a last chunk.

### Observed behavior (including steps to reproduce, if applicable)
While reading a local file as chunks, each api call to write opens the object n time.  (so, `pep_api_replica_open_*`. is triggered n times) I guess this is because of what is explained [here ](https://github.com/irods/irods_client_http_api/issues/185#issuecomment-1864922062).

This behavior is not like what I see in other main clients. Even for example `istream write` opens writes chunks and closes. I guess implementing policies looks would be difficult with its current behavior?

**Comment by korydraughn** [comment]
Using only the `write` operation will result in an open, write, close.

You can achieve what you describe by using the `parallel_write_init`, `write`, and `parallel_write_shutdown` operations. These ops allow you to open a data object and write to it in parallel in whatever order you want. This does require you to manage the offset, avoid overlapping writes, and call `parallel_write_shutdown` though.

See https://slides.com/irods/sc23-irods-http-api-presenting-irods-as-http#/13 for details on to use these operations. I've also posted the example from that slide here for posterity.
```
http_api_url="http://localhost:9000/irods-http-api/0.1.0/data-objects"

# Open 3 streams to the data object, file.bin.
transfer_handle=$(curl -H "Authorization: Bearer $bearer_token" "$http_api_url" \
  --data-urlencode 'op=parallel_write_init'                                     \
  --data-urlencode "lpath=/tempZone/home/rods/file.bin"                         \
  --data-urlencode 'stream-count=3'                                             \
  | jq -r .parallel_write_handle)

# Write "hello" (i.e. 5 bytes) to the data object.
# Notice we didn't specify which stream to use.
curl -H "Authorization: Bearer $bearer_token" "$http_api_url" \
  -F 'op=write'                                               \
  -F "parallel-write-handle=$transfer_handle"                 \
  -F 'count=5'                                                \
  -F 'bytes=hello;type=application/octet-stream'              \
  | jq

# Shutdown all streams and update the catalog.
curl -H "Authorization: Bearer $bearer_token" "$http_api_url" \
  --data-urlencode 'op=parallel_write_shutdown'               \
  --data-urlencode "parallel-write-handle=$transfer_handle"   \
  | jq
```

Keep in mind that if you lose the parallel write handle and fail to call `parallel_write_shutdown`, the data object will remain open until the HTTP API server is shut down.

**Comment by mstfdkmn** [comment]
I haven't tested the parallels yet. But I will. Thanks for examples.

**Comment by korydraughn** [comment]
That's correct.

You can use `write` alone to stream bytes. You just pay for policy running a lot and it's probably not the most efficient solution.

The parallel features get you closer to what you want IMO.

**Comment by korydraughn** [comment]
There's nothing actionable here.

Closing.
