### ISSUE TITLE
Replicating parallel-write-init on the data-objects end-point results in HTTP 400

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_client_http_api#192]
When trying to replicate the `parallel-write-init ` example from the [documentation](https://github.com/irods/irods_client_http_api/blob/38d67aa5ab798952450dc4429c20d82586a375e8/API.md?plain=1#L855C1-L866C4), with the settings as shown below,  I get a Bad Request Response. Is this because multiplexing is not supported by HTTP/1.1?

```
curl http://localhost:9001/irods-http-api/0.1.0/data-objects \
    -H "Authorization: Bearer ${TOKEN}" \
    --data-urlencode 'op=parallel-write-init' \
    --data-urlencode 'lpath=/tempZone/home/rods/y.rds' \
    --data-urlencode 'stream-count=2' \
    -v
```
output:

```
*   Trying 127.0.0.1:9001...
* Connected to localhost (127.0.0.1) port 9001 (#0)
> POST /irods-http-api/0.1.0/data-objects HTTP/1.1
> Host: localhost:9001
> User-Agent: curl/7.81.0
> Accept: */*
> Authorization: Bearer 
> Content-Length: 77
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Server: irods_http_api/0.1.0 [86bad75c3dc6e8f8855a5978bfa43c79f069101c]
< Content-Type: application/json
< Content-Length: **0``**
```

**Comment by trel** [comment]
Have you tried including `truncate=1` and `append=0`?

They're marked as optional, but I'm not sure all the bumpers are in place yet.

**Comment by trel** [comment]
The current test is here... 

https://github.com/irods/irods_client_http_api/blob/38d67aa5ab798952450dc4429c20d82586a375e8/test/test_irods_http_api.py#L930

**Comment by trel** [comment]
The 'Mark bundle as not supporting multiuse' is just a debug message confirming that the HTTP API is not serving as HTTP/2.

https://stackoverflow.com/a/74917358

This trace message has now been removed in curl 7.88.0:
   https://github.com/curl/curl/commit/73477d5a4

**Comment by korydraughn** [comment]
`op=parallel-write-init` should use underscores instead of hyphens (i.e. `op=parallel_write_init`.

The HTTP API does not support anything beyond HTTP/1. This is due to the HTTP library used to implement the server.

See the Boost.Beast FAQ at https://www.boost.org/doc/libs/1_81_0/libs/beast/doc/html/beast/design_choices/faq.html for details.

**Comment by korydraughn** [comment]
Will fix the documentation for the `op` value.

**Comment by trel** [comment]
underscores!   pretty subtle.    might we consider using hyphens instead?

https://www.google.com/search?q=underscores+in+urls

Not convinced yet, but it does appear to be more standard to use hyphens in more places.
