### ISSUE TITLE
Return an error when `bytes` parameter and `count` parameter of write operation do not align

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#194]

**Comment by alanking** [comment]
Possibly related to #188? Just linking for posterity.

**Comment by korydraughn** [comment]
Yes, I created this issue as a result of several others. I didn't link them because it wasn't clear if this issue was the true reason behind the others.

I'm pretty sure this is related though.

**Comment by korydraughn** [comment]
Noting here that we removed the need for the `count` parameter.
