### ISSUE TITLE
 List deprecated parameters in the documentation

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_client_http_api#210]
## Feature

I want to write an object to the iRODS server while developing rirods to use the new API. The operation was failing every time but I did not understand why. It finally dawned to me that I was following the updated documentation not realizing that the `count` parameter is still used in the Docker demo. So my request is to list deprecated parameters in the documentation.

**Comment by trel** [comment]
I think we will start this practice once we get closer to 1.0.   We're still finding the contours.

In the meantime, make sure you're reading the tag you're using...
   https://github.com/irods/irods_client_http_api/tree/0.1.0

**Comment by MartinSchobben** [comment]
Yes, I will do that from now.

**Comment by korydraughn** [comment]
I think we can close this given that this project's API is not stable yet.

**Comment by trel** [comment]
sold.   we promise to make it good :)
