### ISSUE TITLE
Remove unnecessary iRODS TLS config properties

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#251]
The following properties aren't needed for TLS communication with the iRODS server and should be removed.
- `/irods_client/tls/certificate_chain_file`
- `/irods_client/tls/dh_params_file`

**Comment by alanking** [comment]
Do you know whether this is true of the iCommands and other clients as well?

**Comment by korydraughn** [comment]
Yes. This is true of the icommands.

The service account is special though. Only the diffie-hellman params file is optional. The other properties are required.
