### ISSUE TITLE
Difficulty Retrieving Collections with Specific Metadata

### ISSUE THREAD

**Issue by bl000m** [irods/irods_client_http_api#274]
We've found it straightforward to add metadata to a collection by fetching the collection endpoint with the `op=modify_metadata` parameter. However, it's unclear how to retrieve all collections with a specific metadata attribute.

It appears that the collection endpoint with the `op=stat` parameter does not provide information about metadata.

Could you please advise on how we can achieve this?
Thanks for your help

**Comment by trel** [comment]
Can you use the query endpoint to find what you're looking for?

https://github.com/irods/irods_client_http_api/blob/main/API.md#query-operations

Something like...

```
select COLL_NAME, META_COLL_ATTR_NAME, META_COLL_ATTR_VALUE, META_COLL_ATTR_UNITS where META_COLL_ATTR_NAME = 'apples'
```

**Comment by bl000m** [comment]
@trel yes it works perfectly. thanks !

**Comment by trel** [comment]
Oh good.

**Comment by alanking** [comment]
Is this something we should record in one of the Markdown manuals? If so, we can make this a documentation exercise. If not, I think we can close this.

**Comment by korydraughn** [comment]
@trel is correct. GenQuery is the proper tool for what you want.

Closing.
