### ISSUE TITLE
Add operations to manage zones

### ISSUE THREAD

**Issue by farbs03** [irods/irods_client_http_api#277]
- [x] main
- [x] 4-3-stable

This would provide functionality like:
- `iadmin mkzone`
- `iadmin modzone`
- `iadmin modzonecollacl`
- `iadmin rmzone`
- `iadmin lz`

This functionality is needed by the zone management tool.

**Comment by korydraughn** [comment]
Equivalent functionality for `iadmin modzonecollacl` is partially implemented, but disabled until further notice.

See #290 for additional details.
