### ISSUE TITLE
`test_copy_operation_returns_an_error_when_destination_path_is_a_collection` asserts incorrect error codes

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#287]
- [x] main
- [x] 4-3-stable
---
## Testing

The following assertion fails because the operation results in `CAT_NO_ACCESS_PERMISSION`.
https://github.com/irods/irods_client_http_api/blob/48b63758b056e11008a6b1e876f0ed427a3f39c2/test/test_irods_http_api.py#L1076

This one expects `CAT_NAME_EXISTS_AS_COLLECTION`.
https://github.com/irods/irods_client_http_api/blob/48b63758b056e11008a6b1e876f0ed427a3f39c2/test/test_irods_http_api.py#L1108

**Comment by trel** [comment]
if the permissions are correct, i'd expect to see `CAT_NAME_EXISTS_AS_COLLECTION`.   yes?

**Comment by korydraughn** [comment]
Yes. The reason for the first assertion failing is because the iRODS server detects that the rodsuser does not have read permissions on the parent collection of the destination path.

The second assertion fails because the iRODS server detects that the rodsuser is attempting to pass a collection as the destination path instead of a [non-existent] data object.

**Comment by trel** [comment]
okay, so... that seems correct and good.
