### ISSUE TITLE
Rename `/irods_client/buffer_size_in_bytes_for_write_operations` to better express its intent

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#328]
The inclusion of "buffer" in the name is misleading.

A better name is `max_number_of_bytes_per_write_operation`.

**Comment by trel** [comment]
this will require an 'upgrade' to tweak their configuration.   not sure if we're mature enough to demand that go into the README.   i'm thinking... don't worry about it.

**Comment by korydraughn** [comment]
Correct. The schema validation will not allow them to launch the server without changing that property first.

I agree we don't need to worry about providing upgrade logic just yet. We're still in the early phases of nailing things down.

**Comment by trel** [comment]
Ah, right - it just won't start.   Done.
