### ISSUE TITLE
Handle missing `aud` claim in access token

### ISSUE THREAD

**Issue by ll4strw** [irods/irods_client_http_api#375]
[JSON Web Token (JWT) Profile for OAuth 2.0 Access Tokens](https://datatracker.ietf.org/doc/html/rfc9068#section-2.2) states that access tokens in JWT format must present an `aud` claim. However, [Section 4.1.3](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3) of [[RFC7519](https://datatracker.ietf.org/doc/html/rfc7519)], which defines JWTs, states that the use of `aud` claims is optional.

Regardless the interpretation that one can give to the documents reported above, it is important to properly handle the cases in which an IAM server could omit the `aud` claim in its access tokens. In particular, I propose the rejection of any access tokens missing  the `aud` claim.

NB: keycloak is one of the IAM servers which could issue access tokens without `aud` claim.

**Comment by MartinFlores751** [comment]
> Regardless the interpretation that one can give to the documents reported above, it is important to properly handle the cases in which an IAM server could omit the `aud` claim in its access tokens. In particular, I propose the rejection of any access tokens missing the `aud` claim.

This is an interesting case for this particular endpoint. I agree that we should not accept any access token missing the `aud` claim, as this follows best practice in [OAuth 2.0 Security Best Current Practice (Section 4.10.2)](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#name-audience-restricted-access-). Based on how the introspection endpoint works, though, I'm not sure what is best in this particular case.

I'm not sure if enforcing the return of an `aud` would help for the introspection endpoint. `aud` is optional for this particular endpoint, as the authorization server should handle these checks (see [additional context](#additional-context-for-the-introspection-endpoint) for "gotchas"). Based on the configuration of the server, the introspection endpoint might not return the `aud` member at all, even if the access token has an `aud`.

Enforcing `aud` to be present should allow for us to check the existence of an `aud`, however, if this requires appropriate configuration of the authorization server for this, would the authorization server not handle the check itself? Is there a case where some may not be able to enforce the presence of the `aud` member in the introspection endpoint response?

Perhaps a solution would be an opt-out (or opt-in) to a stricter validation of the introspection endpoint response? My concern is not locking others out of using the HTTP API if they cannot change the authorization server's configuration.

Something that may be of note, based on the current configuration of the HTTP API, the introspection endpoint should only be used if local validation of the access token fails (e.g., the access token is not a JWT). This means we would be relying on the introspection endpoint to do most of the validation work in this case.

---

#### Additional context for the Introspection Endpoint

See [OAuth 2.0 Token Introspection](https://datatracker.ietf.org/doc/html/rfc7662) for reference.

It looks like the change suggested is in the `validate_using_introspection_endpoint(...)`. This function uses the introspection endpoint, in which [Section 2.2](https://datatracker.ietf.org/doc/html/rfc7662#section-2.2) shows the response from this endpoint is not a JWT, it is a JSON object. The `aud` member is optional according to this specification.

In [Section 4](https://datatracker.ietf.org/doc/html/rfc7662#section-4), the specification states that several checks must be performed by the authorization server. The following bullet point in particular should be relevant for `aud`:

> o  If the token can be used only at certain resource servers, the authorization server MUST determine whether or not the token can be used at the resource server making the introspection call.

However, I will also note this part in the paragraph following the listed items:

> ... Note that not all of these checks will be applicable to all OAuth 2.0 deployments and it is up to the authorization server to determine which of these checks (and any other checks) apply.

**Comment by korydraughn** [comment]
@MartinFlores751 Please close if complete.
