### ISSUE TITLE
Release connection from connection pool following resource operation

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#39]
iRODS agents cache resource information. If any properties of a resource change or any hierarchies change, the cached information will become stale.

To keep things in sync in the HTTP API, the connection used to change resource information needs to be dropped from the pool.

The connection pool will recreate the connection once requested.

**Comment by trel** [comment]
and we still have to somehow communicate to all the others that the resource information they have may now be out of date.   Do we stale ALL of them and they each check a value somewhere before starting a new API call and let go themselves?  Can we get that without a wasted back and forth to the database?

**Comment by korydraughn** [comment]
You're right. It's not only the agent which the operation happened on. Crap.

Perhaps, we make the iRODS server re-instantiate the resource manager. That avoids the the reconnect situation, but we still need to tell other agents to do the same.

Which means we need a mechanism to broadcast the change to all sibling agents.

This needs to be handled in the iRODS server.

**Comment by trel** [comment]
Yes, the server should remember/have/include a 'stale' flag that is returned on each new API request on existing/all connections... that says... actually, 'drop your brain and try again', or even better... 'here's your new brain, use this'.  saves a back and forth perhaps.

**Comment by trel** [comment]
oh, wait... this only has to be stored in the server, and then each Agent can simply check and refresh itself before honoring an API request.

so we store a timestamp in the database... 'resource_information_last_updated' or something... and then each Agent simply takes responsibility for keeping itself up to date.

**Comment by trel** [comment]
Or just in shared memory.

oh wait… could have multiple servers…

oh but… they could each have a cron to check the database value and keep their own cached version in shared memory.

**Comment by korydraughn** [comment]
Using the database is certainly the easiest way to do it. The downside is that each agent must query the database before executing an API request. That creates unnecessary traffic on the database.

One thing to keep in mind is that this is only an issue if the resources and/or hierarchies are being manipulated in realtime. If admins restrict resource management to off hours, then things aren't as bad. This is an important factor to consider for whatever solution we come up with.

**Comment by trel** [comment]
The alternative to Agents polling… is for each to subscribe to something that gets updates.  Can whiteboard it.

**Comment by korydraughn** [comment]
Just noting here that the connection pool automatically refreshes connections after _N_ seconds.

The frequency of the refresh, _N_, can be adjusted via `"refresh_timeout_in_seconds"` in the configuration file.

While this isn't a perfect solution, admins can at least know that the HTTP API will eventually sync with the catalog.

**Comment by korydraughn** [comment]
Client-driven solution implemented here: irods/irods#7288
