### ISSUE TITLE
Consider adding `--dump-config` option to application

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#47]
This option prints the default configuration (with appropriate placeholders) for the HTTP API.

This also removes the need for a configuration file template.

For example ...
```bash
./irods_http_api --dump-config > config.json
```

clang-format and clang-tidy support this kind of thing, therefore, this idea wouldn't be that surprising to people.

**Comment by trel** [comment]
`--show-config` instead?   No strong preference - we should do what other tools do.

**Comment by korydraughn** [comment]
Good conversation regarding this topic located at https://github.com/irods/irods_client_http_api/pull/57#discussion_r1267458097.
