### ISSUE TITLE
Define minimum must-haves for a release

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#5]

**Comment by trel** [comment]
this can/should be done with milestones, single source of truth.

**Comment by korydraughn** [comment]
You're right.

Since this will be absorbed by the REST API in the irods namespace, perhaps 0.9.5?

Then again, this is a full rewrite which means we should bump it to 1.0.0 ... but that's not what we want either because we haven't settled on the interface.

I think the version number in the REST API repo is biting us.

**Comment by trel** [comment]
well, or this remains a different project and the REST API never makes it past 0.9.4 (or maybe gets a tiny bugfix in the future)...

this would become irods_client_http_api or irods_http_api or irods_client_http_cpp ... 

definitely open for discussion / consensus.

**Comment by korydraughn** [comment]
Closing as we have defined a `Must Have` milestone and the project has been renamed following transfer of ownership.
