### ISSUE TITLE
Add support for TLS between the HTTP API and iRODS

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#55]

**Comment by korydraughn** [comment]
Initial investigation indicates the HTTP API can't support this through its configuration file because the iRODS SSL plugin reads settings from the environment. The plugin does not allow settings to be passed to it.

That means SSL can only be supported by either providing a local .irods/irods_environment.json file or defining environment variables that map to the appropriate members of the `rodsEnv` structure.

Using environment variables isn't horrible, but doesn't allow the HTTP API to be as polished as we'd like.

**Comment by korydraughn** [comment]
Perhaps we can get around this by having the HTTP API server set the environment properties itself on startup.

If the properties are defined in the HTTP API config file, then make the necessary calls to set them in the environment. The call to `getRodsEnv` would pick them up and no one has to worry about managing the environment variables themselves.

iRODS does this today using the `environment_variables` property in server_config.json.

**Comment by trel** [comment]
Having the HTTP API setting environment variables for itself seems fine/normal.   Bet this will work.  Will need to make sure we provide a 'clean' environment, so we don't pollute anything else or accidentally inherit things we don't want (but, also... perhaps inherit things we 'do' want?).

**Comment by korydraughn** [comment]
Very true.

I suspect making the HTTP API set the env vars is safe, assuming it is working in an entirely new environment (because fork-exec / sub-shell / new process).

Changing env vars should not leak into the parent process's space.

**Comment by trel** [comment]
agreed

**Comment by korydraughn** [comment]
If all of this is true (and can be proved), then the only thing needed to support TLS/SSL is the defining the structure of the TLS stanza, figuring out which properties are required, and naming those properties.
