### ISSUE TITLE
HTTP API crashes if iRODS server is restarted

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#60]
API needs to be able to recover.

**Comment by korydraughn** [comment]
I've confirmed that the HTTP API crashes if the iRODS server disappears.

We need to investigate why the connection pool didn't refresh the connections or provide a dedicated solution for the HTTP API.

**Comment by trel** [comment]
Hmm.   Yes, time for some logging...

**Comment by korydraughn** [comment]
We likely need to set a signal handler for `SIGPIPE` in the HTTP API and tweak the connection handling code in the iRODS libs for this issue.

Unfortunately, that means a new version of the iRODS server would be needed.
