### ISSUE TITLE
Server must return 505 error code when incoming request does not use HTTP 1.1

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#74]
The check can happen after the following lines. Do the check near these lines covers all endpoints.
https://github.com/irods/irods_client_http_api/blob/17b8defb32948a8110dceab956b86fc0c476a5f4/src/session.cpp#L97-L105

**Comment by korydraughn** [comment]
Boost.Beast automatically handles this.

To test, run the following:
```
curl --http2-prior-knowledge -v http://localhost:9000/irods-http-api/0.1.0/info
```
`--http2-prior-knowledge` skips negotiation and assumes the server supports HTTP/2.

Closing.

**Comment by trel** [comment]
Can you document here the reply from Boost.Beast / HTTP API when the `--http2-prior-knowledge` is sent?

**Comment by korydraughn** [comment]
Here it is ...
```bash
$ curl --http2-prior-knowledge -v http://localhost:9000/irods-http-api/0.1.0/info 
*   Trying 127.0.0.1:9000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5625ce8de220)
> GET /irods-http-api/0.1.0/info HTTP/2
> Host: localhost:9000
> user-agent: curl/7.68.0
> accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

Without any changes to the HTTP API server, it logs the following and ends the client request.
```
[2023-08-27 16:19:32.699] [P:2854093] [error] [T:2854173] fail: read: bad version
```

**Comment by trel** [comment]
Excellent.   We'll get that into the Usage / README.
