### ISSUE TITLE
Add support for GenQuery2

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#8]

**Comment by trel** [comment]
perhaps with `/query?query-type=genquery2` ?     the default would be `genquery`, for the foreseeable future...

**Comment by korydraughn** [comment]
I hadn't considered the idea of letting **users** choose the implementation.

I was thinking about an option in the config file, but either idea would work. Have to think through the pros and cons of what you've presented.

Also, what do you think about the following alternatives for `query-type`?
- `query-impl-type`
- `query-impl`
- `parser-impl` (I think I'm leaning towards this one because we really made a new parser)

**Comment by trel** [comment]
ah, i see... yeah, perhaps even just `parser` with default `parser=genquery`.

i only thought about the user option since we had talked about the same with `iquest` or the new cli.   the server would have a default as well, but it would honor the one closest to the request/user.  interesting.

**Comment by korydraughn** [comment]
I think `parser` works. And making it a parameter gives the user flexibility if GenQuery2 doesn't support what they need at the time.

I like this idea.

**Comment by trel** [comment]
cool.

also allows us to cleanly navigate a request/response discussion with the server - and elegant fallback or errors if they can't find agreement.

**Comment by korydraughn** [comment]
Just noting here that we need a way to determine API numbers for API plugins.

As of right now, the HTTP API is hard-coded to use `1000001` as the API number for GenQuery2. That integer value will most likely change when GenQuery2 is complete.

Perhaps a way for people in the community to register API numbers. People in the community needing a fixed API number would submit a request to the Consortium. The Consortium would either approve or deny the request. Upon approval, the API number is registered and documented in a public area for all to see.

This isn't a must-have at the moment, so we don't need to worry about this for a beta release.

**Comment by korydraughn** [comment]
Also noting here that using GenQuery2 will require re-compiling with the GenQuery2 package installed.

The reason for this is because we need to include the GenQuery2 header file which isn't available without the package. Of course we could define the necessary structures ourselves, but that can quickly go wrong, so to be on the safe side we're going to have to build in CMake options that trigger the necessary code changes.
