### ISSUE TITLE
Trim operation does not allow trimming to one replica

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#88]
The endpoint operation needs to set `COPIES_KW` to `"1"`.

**Comment by trel** [comment]
Want to make sure this doesn't signal to always trim 'down to' `1` replica.

**Comment by korydraughn** [comment]
That's correct. The `COPIES_KW` is setting the minimum replicas to keep. The HTTP API is modeling what we want the trim operation to be in the future. That is, admins must be explicit about which replica is trimmed. Only one replica can be trimmed by a single request.

**Comment by trel** [comment]
Good good.
