### ISSUE TITLE
Flesh out register operation for data objects endpoint

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#93]
- [x] Support for checksums
- [x] Support for registering as replica
---
- Set keyword for registering as replica
    - `as-replica=<integer>`
- Add support for checksums (local vs remote)
    - `checksum=verify` means the checksum calculation and verification are handled on the server
    - `checksum=<string>` means register the string as the checksum and do verification

**Comment by trel** [comment]
`as-replica=<integer>` is ... not usually what we expose to users.    We let them pick a target resource by name, and then the server does any replica number calculation/decision-making.

**Comment by trel** [comment]
The namespacing around checksum command vs value feels loose in this proposal.   Probably need to discuss.

**Comment by korydraughn** [comment]
> `as-replica=<integer>` is ... not usually what we expose to users. We let them pick a target resource by name, and then the server does any replica number calculation/decision-making.

`as-replica=<integer>` is modeling the behavior of `ireg [--repl]`. The `<integer>` must be 0 or 1.

**Comment by trel** [comment]
Oh, it's a boolean/flag.     Carry on.

**Comment by alanking** [comment]
I had the same experience and read `as-replica` to mean "as replica number <integer>". I think it makes sense, just had to take a second to realize it's a flag as well.

Some possible alternatives...
- `as-replica`
- `as-new-replica`
- `object-exists`
- `as-replica-on-existing-object`

Or, flip it on its head...
- `new-data-object` (defaults to 1; 0 is equivalent to using `--repl` flag)

**Comment by korydraughn** [comment]
Out of all the proposed names, `as-replica` and `as-new-replica` sound the best to me.

The `new-data-object` idea is interesting, but it doesn't seem better than the other two options.

**Comment by trel** [comment]
`as-new-replica` or perhaps even...

`as-additional-replica`, since all registration of new data objects are also technically a new replica.

**Comment by korydraughn** [comment]
In regard to the `checksum` parameter, we've learned `REG_CHKSUM_KW` and `VERIFY_CHKSUM_KW` result in identical behavior.

See https://github.com/irods/irods/blob/198873a0c2ac137ec6cbe18bff314bc34b8db311/plugins/api/src/register_physical_path.cpp#L351-L361.

Both keywords instruct the registration API endpoint in the iRODS server to calculate and store a checksum.

Therefore, the `checksum` parameter provided by the HTTP API should be a boolean and only take `0` and `1` as valid values.

**Comment by korydraughn** [comment]
Still need to settle on the naming of `as-replica` parameter.

**Comment by korydraughn** [comment]
Going with `as-additional-replica`.
