### ISSUE TITLE
Remove `max_` from `max_[r,w]buffer_size_in_bytes` properties in config file

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_client_http_api#97]
The word **max** is misleading and should be removed.

The properties in question explicitly define the size of internal I/O buffers, therefore the word **max** is irrelevant.

**Comment by trel** [comment]
please consider adding more letters...
- `read_buffer_size_in_bytes`
- `write_buffer_size_in_bytes`

or whether rbuffer and wbuffer are 'standard' enough for readers.

**Comment by korydraughn** [comment]
Sure thing.

**Comment by korydraughn** [comment]
I'm starting to think **max** is correct based on the current implementation.

As of 85bb529, both of these properties act as an upper bound on the number of bytes that can be read or written.

`max_rbuffer_size_in_bytes` really is the max number of bytes that can be read in a single read of a data object. Requesting more bytes than what's allowed results in an error.

`max_wbuffer_size_in_bytes` represents a chunk size. Clients are allowed to more bytes than can be written in one go. The HTTP API server will write the payload in sequential chunks until all bytes have been written.

So, I think **max** is ok/fine. If anything, perhaps the names need to be changed to reflect what they're actually for.

**Comment by trel** [comment]
Changing them is definitely encouraged if they would be better named with new names.

Want to propose a few?

**Comment by korydraughn** [comment]
Sure. Feel free to go ahead and post ideas. I need to think on it.

**Comment by korydraughn** [comment]
Proposing ...
- `max_number_of_bytes_per_read_operation`
- `buffer_size_for_write_operations`

**Comment by trel** [comment]
Add `_in_bytes` to write?
